Arquisoft/lomap_es3a

README.md

Añadidos desarrolladores al README

07/02/2023 - Omar - Updated README

---

README.md

Fixes #21. Se ha añadido el logo del proyecto al README, además de crear una sección para la descripción del proyecto.

12/02/2023 - Omar - Añadido el logo del proyecto

---

docs/01_introduction_and_goals.adoc

Fixes #4. Se ha redactado el documento "Introduction and goals".

13/02/2023 - Omar - Redacción de Introducción

---

docs/02_architecture_constraints.adoc

Fixes #10. Subida del segundo documento.

13/02/2023 - Omar - Redacción de Restricciones

---

README.md

Fixes #33. Actualizar README y añadidas marcas registradas.

13/02/2023 - Omar - Actualizado README con nuevo wallpaper

---

docs/03_system_scope_and_context.adoc

Fixes #11. Se ha redactado el apartado destinado  al Alcance y contexto del sistema

15/02/2023 - David - Terminado apartado 3 documentación

---

docs/06_runtime_view.adoc

Fixes #14 . Terminado el apartado de la documentación referente a la vista de ejecución.

15/02/2023 - David - Terminado apartado 6 documentación

---

docs/04_solution_strategy.adoc

Fixes #12. Redacción de la estrategia de solución.

15/02/2023 - Carlos - Terminado apartado 4 documentación

---

docs/05_building_block_view.adoc

Fixes #13. Se ha redactado la parte destinada a la vista de bloques.

15/02/2023 - Omar - Terminada parte 5 de la documentacion

---

docs/12_glossary.adoc

Fixes #20. Redactado el glosario de la documentación.

15/02/2023 - Omar - Terminado apartado 12 documentación

---

docs/09_design_decisions.adoc

Fixes #17. Terminado el redactado del documento de las decisiones de diseño.

15/02/2023 - Raúl - Terminado apartado 9 documentación

---

docs/11_technical_risks.adoc

Fixes #19. Terminado el redactado de la documentación sobre los riesgos técnicos.

16/02/2023 - Raúl - Terminado apartado 11 documentación

---

docs/07_deployment_view.adoc

Fixes #15. Terminada la documentación de la vista de despliegue

16/02/2023 - Carlos - Terminado apartado 7 documentación

---

docs/08_concepts.adoc

Fixes #56. Se ha corregido la errata correspondiente

17/02/2023 - Omar - Corregida errata en el documento 8

---

docs/01_introduction_and_goals.adoc
docs/05_building_block_view.adoc

Fixes #43. Se ha creado la primera versión de la documentación, generándola correctamente y haciendo una revisión de que todo estaba correctamente realizado.

18/02/2023 - General - Corregidos últimos errores de la documentación

---

docs/02_architecture_constraints.adoc

Fixed #70. Expresión sobre la incidencia de cambio de tamaños de grupo suavizada.

20/02/2023 - David - Corregida expresión reestructuración.

---

README.md

Fixes #30. Se ha mejorado el README, añadiendo las etiquetas de valoración, mejorando la descripción del proyeco y añadiendo los primeros enlaces importantes.

26/02/2023 - Omar - Actualizado el README

---

docs/04_solution_strategy.adoc
docs/09_design_decisions.adoc
docs/package-lock.json
package-lock.json

Fixes #89. Se han corregido errores, añadiendo actualizaciones en las decisiones del proyecto.

06/03/2023 - Omar - Corregidos errores en la documentación

---

webapp/src/components/map/options/OptionsPanel.tsx
webapp/src/components/map/options/Search.tsx
webapp/src/css/map.css

Fixes #111. Se ha creado el búscador de marcadores en el panel de opciones.

12/03/2023 - Omar - Creación del buscador

---

webapp/src/components/map/LocationMarker.tsx
webapp/src/components/map/MarkerPanel.tsx
webapp/src/components/map/options/Comments.tsx
webapp/src/components/map/options/NamePlace.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/css/map.css

Fixes #95. Se ha creado el panel de home.
Fixes #100. Se ha creado el panel del mapa.

13/03/2023 - General - Crear el panel de Home y del Mapa

---

webapp/src/components/home/HomePage.tsx
webapp/src/components/home/MainScreen.tsx
webapp/src/components/map/Notification.tsx
webapp/src/css/notificacion.css

Fixes #141  . Se ha añadido la primera notificación al sistema

PR: 15/03/2023 - Raúl - Añadida primera versión notificaciones

---

README.md

Fixes #151. Se han centrado las etiquetas del readme

19/03/2023 - Omar - Centradas etiquetas de calidad

---

README.md

Fixes #153. Se ha añadido el footer al README

19/03/2023 - Omar - Añadido footer de Arquisoft

---

webapp/src/components/map/LocationMarker.tsx
webapp/src/components/map/Map.tsx
webapp/src/components/map/MarkerPanel.tsx
webapp/src/components/map/options/Coordinates.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/components/pod/MarkersPOD.tsx
webapp/src/components/pod/Point.ts
webapp/src/css/map.css
webapp/src/shared/shareddtypes.ts

Fixes #162 . Se ha implementado la funcionalidad que permite, además de la información, también guardar las coordenadas de los marcadores en el POD

26/03/2023 - Carlos - Implementada funcionalidad para que, además de la información, también se guarden las coordenadas de los marcadores en el POD 

---

webapp/src/components/pod/MarkersPOD.tsx

Desarrollada funcionalidad que permite ver en el mapa los marcadores guardados en el POD del usuario
Fixes #158 . Se ha desarrollado la funcionalidad que permite ver en el mapa los marcadores guardados en el POD del usuario

26/03/2023 - Carlos - Desarrollada funcionalidad que permite ver en el mapa los marcadores guardados en el POD del usuario

---

README.md

Fixes #168. Se han mejorado los enlaces del README.

 26/03/2023 - Omar - Mejorados enlaces

---

README.md

Fixes #170. Se ha añadido la pila de tecnologías al README del proyecto.

26/03/2023 - Omar - Añadida pila de tecnologías

---

README.md

Fixes #94. Se han añadido las instrucciones de despliegue al README.

26/03/2023 - Omar - Añadidas instrucciones de despliegue

---

README.md
designs/footer.svg

Fixes #174. Se ha añadido el footer en movimiento al readme.

26/03/2023 - Omar - Añadido footer en movimiento

---

webapp/src/components/home/HomePage.tsx

Se ha cambiado el idioma de las notificaciones de Español a Ingles.

PR: 26/03/2023 - Raúl - Cambio de idioma  en notificaciones

---

webapp/src/components/home/HomePage.tsx
webapp/src/components/pod/ButtonAddPod.tsx

Añadida notificacion en el boton de Marcador

PR: 26/03/2023 - Raúl - Añadida notificación para crear Marcador

---

webapp/src/components/map/LocationMarker.tsx
webapp/src/components/map/Map.tsx
webapp/src/components/map/MapPage.tsx
webapp/src/components/map/MarkerPanel.tsx
webapp/src/components/pod/ButtonAddPod.tsx

Arreglado problema boton desaparición antes de tiempo

26/03/2023 - Raúl - Solucionado problema notificacion boton

---

webapp/src/components/pod/ButtonAddPod.tsx

Fixes #183  . Se ha añadido notificacion para cada marcador guardado en POD

27/03/2023 - Raúl - Notificación ahora aparece para cada marcador guardado en POD

---

webapp/src/components/home/HomePage.tsx
webapp/src/components/map/Notification.tsx
webapp/src/components/pod/ButtonAddPod.tsx

Fixes #187 . Se ha arreglado guardando el estado en el navegador de tal forma que solo aparece la primera vez que visitas la web

27/03/2023 - Raúl - Notificacion de bienvenida almacena en Navegador

---

docs/07_deployment_view.adoc

Fixes #190. Se ha corregido el error de los estándares del diagrama 7.

27/03/2023 - Omar - Corregido error de los estándares del diagrama 7 

---

README.md

27/06/2023 - Raúl - Animaciones README

---

README.md

Actualización README con animacion para Arquisoft footer

28/06/2023 - Raúl - Actualización README con animacion para Arquisoft

---

.idea/workspace.xml
webapp/src/App.tsx
webapp/src/components/home/HomePage.tsx
webapp/src/components/map/LocationMarker.tsx
webapp/src/components/map/Map.tsx
webapp/src/components/map/MapPage.tsx
webapp/src/components/map/MarkerPanel.tsx
webapp/src/components/map/Notification.tsx
webapp/src/components/map/options/Coordinates.tsx
webapp/src/components/map/options/DeveloperTeam.test.tsx
webapp/src/components/map/options/Score.tsx
webapp/src/components/navigation/LanguageMenu.tsx
webapp/src/components/navigation/NavBar.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/components/pod/MarkersPOD.tsx
webapp/src/components/pod/Point.ts
webapp/src/css/map.css
webapp/src/css/notificacion.css

Prueba de corrección de tests y errores.

30/03/2023 - Omar - Prueba de covertura y tests

---

.idea/workspace.xml
webapp/src/App.css
webapp/src/App.tsx
webapp/src/components/navigation/NavBar.tsx

03/04/2023 - Raúl - Creado Switch para DarkMode.

---

docs/01_introduction_and_goals.adoc
docs/03_system_scope_and_context.adoc
docs/04_solution_strategy.adoc
docs/05_building_block_view.adoc
docs/06_runtime_view.adoc
docs/07_deployment_view.adoc
docs/08_concepts.adoc
docs/09_design_decisions.adoc
docs/11_technical_risks.adoc
docs/12_glossary.adoc

Fixes #215. Se han eliminado todas las menciones a la base de datos de la documentación.

06/04/2023 - Omar - Borradas menciones a base de datos

---

docs/07_deployment_view.adoc

Fixes #75. Se ha corregido el diagrama de la sección 7, siguiendo los estándares.

06/04/2023 - Omar - Corregido diagrama 7

---

docs/05_building_block_view.adoc

Fixes #74. Se ha corregido el diagrama de la seccion 3.

07/04/2023 - Omar - Corregido diagrama sección 3

---

docs/01_introduction_and_goals.adoc
docs/04_solution_strategy.adoc
docs/10_quality_scenarios.adoc

Fixes #219. Se ha cambiado el rendimiento como quality goal, de forma que ahora se ha elegido la escalabilidad.

07/04/2023 - Omar - Corregido el quality goal

---

docs/03_system_scope_and_context.adoc

Fixes #71. Se ha realizado el diagrama de contexto técnico.

07/04/2023 - Omar - Realizado diagrama de contexto técnico

---

docs/06_runtime_view.adoc

Fixes #222. Se han corregido los errores de interacción con los PODs en los diagramas de secuencia.

07/04/2023 - Omar - Corregidos diagramas de secuencia

---

webapp/src/components/map/MarkerPanel.tsx
webapp/src/components/map/options/Filter.tsx
webapp/src/components/map/options/OptionsPanel.tsx
webapp/src/components/navigation/NavBar.tsx
webapp/src/css/map.css
webapp/src/shared/shareddtypes.ts

Fixes #231. Se ha arreglado el bug visual, mejorando la apariencia del menu de opciones del mapa.

08/04/2023 - Omar - Arreglado el bug visual

---

webapp/src/components/map/LocationMarker.tsx
webapp/src/components/map/MarkerPanel.tsx
webapp/src/components/map/options/NamePlace.tsx
webapp/src/components/map/options/OptionsPanel.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/css/map.css

Fixes #238. Se ha modificado el menu de añadir un marcador, haciendo que siga los diseños propuestos y evite probleamas de adaptabilidad.

 08/04/2023 - Omar - Modificado el menu de añadir un marcador

---

webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/components/pod/MarkersPOD.tsx

Añadida información en el PopUp de los marcadores mostrando autor imagen descripcion y puntuación en una interfaz

08/04/2023 - Raúl - PopUp de Marcadores con toda la información y imagen

---

webapp/src/test/home/DocumentationButton.test.tsx

Fixes #244. Se ha realizado test sobre el botón de documentación.

09/04/2023 - Omar - Realizado test sobre el botón de documentación

---

webapp/src/components/home/DescriptionText.tsx
webapp/src/components/home/HomeScreen.tsx
webapp/src/components/pod/FriendsPOD.ts
webapp/src/css/home.css
webapp/src/test/home/DescriptionText.test.tsx

Fixes #242. Se ha realizado el test de la descripción.

09/04/2023 - Omar - Realizado test de la descripción

---

webapp/src/components/home/DocumentationButton.tsx
webapp/src/components/home/HomeScreen.tsx
webapp/src/components/home/TechStack.tsx
webapp/src/shared/shareddtypes.ts
webapp/src/test/home/DocumentationButton.test.tsx
webapp/src/test/home/TechButton.test.tsx
webapp/src/test/home/TechStack.test.tsx

Fixes #245. Se ha realizado el test de la pila de tecnologías.

 09/04/2023 - Omar - Realizado test de la pila de tecnologías

---

webapp/src/App.tsx
webapp/src/components/FooterInfo.tsx
webapp/src/components/home/DescriptionText.tsx
webapp/src/components/home/DocumentationButton.tsx
webapp/src/components/home/HomePage.tsx
webapp/src/components/home/TechStack.tsx
webapp/src/components/map/MarkerPanel.tsx
webapp/src/components/map/options/Comments.tsx
webapp/src/components/map/options/Coordinates.tsx
webapp/src/components/map/options/Filter.tsx
webapp/src/components/map/options/NamePlace.tsx
webapp/src/components/map/options/OptionsPanel.tsx
webapp/src/components/map/options/Search.tsx
webapp/src/components/navigation/LanguageMenu.tsx
webapp/src/components/navigation/NavBar.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/test/FooterInfo.test.tsx
webapp/src/test/home/DescriptionText.test.tsx
webapp/src/test/home/DocumentationButton.test.tsx
webapp/src/test/home/TechStack.test.tsx

Se han corregido los errores de los tests.

09/04/2023 - Omar - Corregidos errores para los tests

---

docs/03_system_scope_and_context.adoc

Fixes #279. Se ha corregido el diagrama de contexto técnico.

10/04/2023 - Omar - Corregido diagrama de contexto técnico

---

webapp/src/components/map/OptionsPanel.tsx
webapp/src/components/pod/ButtonAddPod.tsx

Fixes #284  . Se ha arreglado el bug que no actualizaba el componente FriendList al añadir un marcador

12/04/2023 - Carlos - Arreglado bug que no actualizaba el componente FriendList al añadir un marcador

---

webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/components/pod/FriendList.tsx

Fixes #288  . Se ha arreglado el bug que no muestra ningún marcador al añadir uno si se tiene aplicado un filtro a los marcadores de los amigos

15/04/2023 - Carlos - Arreglado bug que no muestra ningún marcador al añadir uno si se tiene aplicado un filtro a los marcadores de los amigos

---

webapp/src/components/navigation/NavBar.tsx

Fixes #290  . Se ha Creado el sistema de control para el usuario con Login incluido.

16/04/2023 - Raúl - Añadido sistema Login con control para el usuario

---

webapp/src/components/navigation/NavBar.tsx

Fixes #292  . Se ha modificado para que el avatar aparezca solo al loguearse

16/04/2023 - Raúl - Modificado avatar solo aparece tras loguearse

---

webapp/package-lock.json
webapp/src/components/navigation/NavBar.tsx

Fixes #292  . Se ha añadido el sistema de control mas el nombre de usuario cogido desde el POD

17/04/2023 - Raúl - Añadido nombre POD con el login

---

webapp/src/components/map/MarkerPanel.tsx
webapp/src/components/map/OptionsPanel.tsx
webapp/src/components/map/options/Mark.tsx
webapp/src/shared/shareddtypes.ts

Fixes #298  . Se ha arreglado el bug que no permitía guardar la puntuación del marcador en el POD

17/04/2023 - Carlos - Arreglado bug que no permitía guardar la puntuación del marcador en el POD

---

webapp/package-lock.json
webapp/src/components/navigation/NavBar.tsx

Fixes #302  . Se ha añadido la imagen de usuario desde el POD

18/04/2023 - Raúl - Añadido imagen de perfil desde el POD

---

webapp/src/components/UserProfile.tsx
webapp/src/components/navigation/NavBar.tsx

Fixes #304  . Se ha completado la issue 304, añadir informacion a la vista perfil desde el POD

18/04/2023 - Raúl - Añadida información del POD al perfil

---

webapp/src/components/pod/ButtonAddPod.tsx

Fixes #312  . Se ha solucionado el bug que impide añadir el primer marcador al POD cuando la cuenta es nueva

19/04/2023 - Carlos - Solucionado bug que no permitía añadir el primer marcador al POD

---

webapp/src/components/navigation/OurAvatar.tsx

Se han hecho arreglos en el nuevo componente para la refactorización

21/04/2023 - Raúl - Arreglos componente para refactorizacon Avatar

---

webapp/src/components/navigation/NavBar.tsx

Fixes #322  . Se ha añadido el nuevo componente para la refactorización al Navbar y realizado todos los cambios necesarios

21/04/2023 - Raúl - Refactorización NavBar para mantenibilidad

---

webapp/src/components/navigation/NavBar.tsx

Raúl - Eliminados imports no usados y warnings en el navBar

21/04/2023 - Raúl - Eliminados imports no usados y warnings

---

webapp/src/components/ImgbbUploader.tsx

Fixes #338  . Se ha crado el nuevo componente para subir imagenes al nuevo formato del POD

23/04/2023 - Raúl - Componente para subir imagenes

---

webapp/src/components/ImgbbUploader.tsx
webapp/src/components/navigation/OurAvatar.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/css/map.css
webapp/src/languages/language_ast.json
webapp/src/languages/language_chn.json
webapp/src/languages/language_deu.json
webapp/src/languages/language_en.json
webapp/src/languages/language_es.json
webapp/src/languages/language_fr.json

Fixes #340  . Se ha internacionalizado el perfil y la subida de foto además de arreglado algun warning

23/04/2023 - Raúl - Añadida la traduccion del Perfil y de subida de Foto

---

webapp/src/components/navigation/OurAvatar.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/css/map.css
webapp/src/languages/language_ast.json
webapp/src/languages/language_chn.json
webapp/src/languages/language_deu.json
webapp/src/languages/language_en.json
webapp/src/languages/language_es.json
webapp/src/languages/language_fr.json

Se ha mejorado el menu de usuario, se ha añadido la nueva internacionalización y cambiado el contenedor de las fotos ahora tienen un tamaño fijo da igual la imagen

23/04/2023 - Raúl - Mejorado menu usuario y movido el photo upload

---

webapp/src/components/pod/ButtonAddPod.tsx

23/04/2023 - Raúl - Arreglado alto de la foto

---

webapp/src/components/map/AddMarkerPanel.tsx
webapp/src/components/map/options/Comments.tsx
webapp/src/components/map/options/Coordinates.tsx
webapp/src/css/friends.css
webapp/src/languages/language_ast.json
webapp/src/languages/language_chn.json
webapp/src/languages/language_deu.json
webapp/src/languages/language_en.json
webapp/src/languages/language_es.json
webapp/src/languages/language_fr.json

Fixes #346  . Se ha actualizado panel de añadir marcador

24/04/2023 - Carlos - Actualizado panel de añadir marcador

---

webapp/src/components/friends/ManageFriends.tsx
webapp/src/components/pod/ButtonAddPod.tsx

Se han solucionado errores de código

27/04/2023 - Carlos - Solucionados errores de código

---

webapp/src/components/Notification.tsx
webapp/src/test/Notification.test.tsx

28/04/2023 - Omar - Corregido error de tests

---

webapp/package-lock.json
webapp/package.json
webapp/src/components/UserProfile.tsx
webapp/src/components/navigation/LanguageMenu.tsx
webapp/src/test/home/DocumentationButton.test.tsx
webapp/src/test/navigation/LanguageMenu.test.tsx

Fixes #365. Se han realizado test sobre el menú de lenguaje.

28/04/2023 - Omar - Realizado test del menu de lenguaje

---

webapp/src/components/UserProfile.tsx
webapp/src/components/friends/ManageFriends.tsx
webapp/src/css/friends.css
webapp/src/css/profile.css
webapp/src/test/UserProfile.test.tsx

Fixes #363. Se ha realizado el test sobre el perfil del usuario

28/04/2023 - Omar - Realizado test sobre el perfil del usuario

---

webapp/src/components/Notification.tsx
webapp/src/components/navigation/NavBar.tsx
webapp/src/test/Notification.test.tsx
webapp/src/test/UserProfile.test.tsx
webapp/src/test/home/FooterInfo.test.tsx
webapp/src/test/home/ImgCarousel.test.tsx
webapp/src/test/home/TechButton.test.tsx
webapp/src/test/home/TechStack.test.tsx
webapp/src/test/navigation/LanguageMenu.test.tsx
webapp/src/test/navigation/NavBar.test.tsx

Se han aumentado el numero de test para incrementar el code coverage

29/04/2023 - Omar - Aumentados los tests

---

webapp/package-lock.json
webapp/package.json
webapp/src/components/friends/ManageFriends.tsx
webapp/src/test/friends/ManageFriends.test.tsx

Fixes #37.0 Se han hecho unos primeros tests sobre el panel de amigos

29/04/2023 - Omar - Realizados tests sobre panel de amigos

---

webapp/src/components/UserProfile.tsx
webapp/src/components/friends/ManageFriends.tsx
webapp/src/components/map/LocationMarker.tsx
webapp/src/components/map/MapView.tsx
webapp/src/components/map/OptionsPanel.tsx
webapp/src/components/map/options/Filter.tsx
webapp/src/components/map/options/MapSelector.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/components/pod/FriendList.tsx
webapp/src/components/pod/FriendsPOD.ts
webapp/src/components/pod/MarkersPOD.tsx
webapp/src/components/pod/PODsInteraction.ts
webapp/src/languages/language_ast.json
webapp/src/languages/language_chn.json
webapp/src/languages/language_deu.json
webapp/src/languages/language_en.json
webapp/src/languages/language_es.json
webapp/src/languages/language_fr.json

Fixes #401  . Se ha refactorizado el código para que las funciones que interactúan con el POD estén en un fichero a parte y se han realizado mejoras referentes a control de posibles errores

29/04/2023 - Carlos - Se ha refactorizado el código para que las funciones que interactúan con el POD estén en un fichero a parte

---

webapp/src/components/map/MapView.tsx
webapp/src/components/pod/ButtonAddPod.tsx
webapp/src/components/pod/PODsInteraction.ts
webapp/src/languages/language_ast.json
webapp/src/languages/language_chn.json
webapp/src/languages/language_deu.json
webapp/src/languages/language_en.json
webapp/src/languages/language_es.json
webapp/src/languages/language_fr.json

Fixes #409  . Se ha implementado la funcionalidad que no permite al usuario añadir un marcador sin nombre

01/05/2023 - Carlos - Implementada la funcionalidad que no permite al usuario añadir un marcador sin nombre

---

webapp/src/components/help/ContactForm.tsx

01/05/2023 - Raúl - Email corporativo añadido

---

webapp/src/components/friends/ManageFriends.tsx
webapp/src/components/map/ShowMarkerPanel.tsx
webapp/src/components/map/options/FriendList.tsx
webapp/src/components/navigation/LanguageMenu.tsx
webapp/src/components/profile/UserProfile.tsx

02/05/2023 - Carlos - Revisión de bugs
